version: "3.9"

services:
  mlflow_example:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: mlflow_example:$USER
    container_name: mlflow_example_$USER
    environment:
      - USERNAME=$USER
      - USER=$USER
    working_dir: /app
    volumes:
      - ./:/app
    command: python run_experiments.py
