ClusterName=gpu-lab-slurm
SlurmctldHost=epda6tu7ep1dopeif204
AuthType=auth/munge
CryptoType=crypto/munge
ProctrackType=proctrack/linuxproc
SwitchType=switch/none
MpiDefault=none
TaskPlugin=task/none
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
GresTypes=gpu
SlurmctldPort=6817
SlurmdPort=6818
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldDebug=info
SlurmdDebug=info
StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
ReturnToService=2
SchedulerType=sched/backfill
NodeName=epda6tu7ep1dopeif204 CPUs=8 RealMemory=30091 Gres=gpu:tesla_t4:1 State=UNKNOWN
PartitionName=gpu Nodes=epda6tu7ep1dopeif204 Default=YES MaxTime=01:00:00 State=UP
